FROM quay.io/quarkus/centos-quarkus-maven:19.3.1-java8
USER root
COPY src /usr/src/app/src
#RUN mvn -f /usr/src/app/pom.xml -Pnative clean verify
RUN /usr/src/app/src/gradlew build -Dquarkus.package.type=native
